import { Poppins } from "next/font/google";
import "./globals.css";
import AerouiThemeProvider from "./theme-provider";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]  
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <AerouiThemeProvider> 
          {children}
        </AerouiThemeProvider>
      </body>
    </html>
  );
}
